Convert more files to ts
NuroDev/platforms pull request #2
Opened 2022-01-25 21:26 UTC by GuidoOffermans

Heya, i've tried to convert a couple files :) There are some type-errors left where i was not sure how to solve them, sorry for that.
I could definitely use some pointers with Next/image types!

2022-01-26 10:57 UTC, NuroDev requested changes

2022-01-26 10:57 UTC, NuroDev commented on components/sites/Layout.tsx
> +import { Meta } from "@/types";
Could do with `import type` here

2022-01-26 10:57 UTC, NuroDev commented on lib/twitter-media.ts
> +      (variant: any ) => variant.content_type === "video/mp4"
I think for this we could either manually create type declarations based on the Twitter API or use `unknown` instead as I feel that is better fitting

2022-01-26 10:57 UTC, NuroDev commented on lib/twitter.ts
> +import {Tweet} from "@/types/twitter";
Again, could do with an `import type` here

2022-01-26 10:57 UTC, NuroDev commented on lib/twitter.ts
> +    tweet.includes.media.find((media: any) => media.media_key === key)
Again, could probably either manually declare the types or use `unknown` for the `media`'s type

2022-01-26 10:57 UTC, NuroDev commented on pages/_sites/[site]/[slug].tsx
> +  const meta: Meta = {
I usually prefer to assert types here rather than annotate them.

2022-01-26 10:57 UTC, NuroDev commented on pages/app/site/[id]/settings.tsx
> +type siteData = {
Usually prefer use of `interface`'s here ([Reason](https://twitter.com/jaredpalmer/status/1331695529470922754?s=20))
```suggestion
interface SiteData {
```

2022-01-26 10:57 UTC, NuroDev commented on types/twitter.ts
> +export type Tweet = Record<string, any>
For external API's I usually go one of two routes:
 1) Use `unknown`
 2) Check the docs & `console.log` a response to hackily create a rough API response type definition.

2022-01-26 11:04 UTC, NuroDev commented
> I could definitely use some pointers with Next/image types!

As for the `<Image />` in `Layout.tsx` I think the best way to handle it safely is to conditionally render the `<Image />` component based on whether `meta.logo` is defined or not. If not we can probably failover to some kind of placeholder.
I have been using the following code snippet in a few other places already to just have SOMETHING to show:
```html
<div className="absolute flex items-center justify-center w-full h-full bg-gray-100 text-gray-500 text-4xl">
	?
</div>
```

2022-01-26 11:24 UTC, NuroDev commented on pages/app/site/[id]/settings.tsx
> +                onInput={(e: React.ChangeEvent<HTMLInputElement>) =>
This should use `HTMLTextAreaElement` instead of `HTMLInputElement`

2022-01-26 11:34 UTC, Rocinante89 commented
@NuroDev maybe using the vercel logo as a default might be an idea?

2022-01-27 20:40 UTC, GuidoOffermans commented
Thanks for the review! I've been busy with my daytime job 😅. I'll dive into it tomorrow

2022-01-28 21:36 UTC, NuroDev commented
Closing this as I have gone though & added the migrations myself.

2022-01-28 21:36 UTC, closed without merging